-- =============================================================
-- NEXUSGOV IDENTITY ISSUANCE SYSTEM — AUTOMATIC DATABASE BACKUP
-- Generated / Synced: 2026-09-30T10:46:14.136587500
-- =============================================================

SET FOREIGN_KEY_CHECKS = 0;

INSERT IGNORE INTO `users` (`user_id`, `username`, `password_hash`, `full_name`, `email`, `role`, `created_at`) VALUES (1, 'thilina_admin', '$2b$10$q0.x5xM4G2yR/v.3yq1q.Oq4h9sT0g4j6m7k8l9o0p1q2r3s4t5u6', 'Thilina Sakalasooriya', 'thilinasakalasooriya@gmail.com', 'Form-Officer', NOW());
INSERT IGNORE INTO `users` (`user_id`, `username`, `password_hash`, `full_name`, `email`, `role`, `created_at`) VALUES (2, 'admin', '$2b$10$q0.x5xM4G2yR/v.3yq1q.Oq4h9sT0g4j6m7k8l9o0p1q2r3s4t5u6', 'System Admin', 'admin@nexusgov.lk', 'Admin', NOW());
INSERT IGNORE INTO `users` (`user_id`, `username`, `password_hash`, `full_name`, `email`, `role`, `created_at`) VALUES (67, 'form_officer', '$2b$10$q0.x5xM4G2yR/v.3yq1q.Oq4h9sT0g4j6m7k8l9o0p1q2r3s4t5u6', 'Form Handling Officer Perera', 'form-officer@nexusgov.lk', 'Form-Officer', NOW());
INSERT IGNORE INTO `users` (`user_id`, `username`, `password_hash`, `full_name`, `email`, `role`, `created_at`) VALUES (68, 'document_officer', '$2b$10$q0.x5xM4G2yR/v.3yq1q.Oq4h9sT0g4j6m7k8l9o0p1q2r3s4t5u6', 'Document Handling Officer Silva', 'document-officer@nexusgov.lk', 'Document-Officer', NOW());
INSERT IGNORE INTO `users` (`user_id`, `username`, `password_hash`, `full_name`, `email`, `role`, `created_at`) VALUES (69, 'approver', '$2b$10$q0.x5xM4G2yR/v.3yq1q.Oq4h9sT0g4j6m7k8l9o0p1q2r3s4t5u6', 'Senior Approver Jayawardena', 'approver@nexusgov.lk', 'Approver', NOW());
INSERT IGNORE INTO `users` (`user_id`, `username`, `password_hash`, `full_name`, `email`, `role`, `created_at`) VALUES (70, 'operational', '$2b$10$q0.x5xM4G2yR/v.3yq1q.Oq4h9sT0g4j6m7k8l9o0p1q2r3s4t5u6', 'Operational Specialist Silva', 'operational@nexusgov.lk', 'Operational', NOW());
INSERT INTO `applicants` (`applicant_id`, `national_id_number`, `first_name`, `last_name`, `date_of_birth`, `gender`, `address`, `phone_number`, `email`, `registered_at`) VALUES (1, '200509055367', 'Thilina', 'Sakalasooriya', '2005-03-31', 'Male', 'test address 1', '0712513663', 'kgnadunnimesh@gmail.com', NOW()) ON DUPLICATE KEY UPDATE `first_name`=VALUES(`first_name`);
INSERT INTO `applicants` (`applicant_id`, `national_id_number`, `first_name`, `last_name`, `date_of_birth`, `gender`, `address`, `phone_number`, `email`, `registered_at`) VALUES (2, '200200461849', 'KULASINGHA', 'GAMAGE NADUN NIMESH', '2002-01-04', 'Male', '65/6,siyambalape waththa,dewala rd,delgoda', '0703064656', 'kgnadunnimesh@gmail.com', NOW()) ON DUPLICATE KEY UPDATE `first_name`=VALUES(`first_name`);
INSERT INTO `applicants` (`applicant_id`, `national_id_number`, `first_name`, `last_name`, `date_of_birth`, `gender`, `address`, `phone_number`, `email`, `registered_at`) VALUES (3, '200015613237', 'Nimesh', 'namnugama', '2000-06-04', 'Male', 'test address', '071 251 3663', 'sakaleyt@gmail.com', NOW()) ON DUPLICATE KEY UPDATE `first_name`=VALUES(`first_name`);
INSERT INTO `applicants` (`applicant_id`, `national_id_number`, `first_name`, `last_name`, `date_of_birth`, `gender`, `address`, `phone_number`, `email`, `registered_at`) VALUES (9002, '200502273667', 'Thilina', 'Sakalasooriya', '2005-01-22', 'Male', 'test ', '0712513663', 'kgnadunnimesh@gmail.com', NOW()) ON DUPLICATE KEY UPDATE `first_name`=VALUES(`first_name`);
INSERT INTO `applications` (`application_id`, `applicant_id`, `application_type`, `status`, `assigned_officer`, `application_reason`, `marital_status`, `service_type`, `remarks`, `submitted_at`) VALUES (1, 1, 'New', '', 'Thilina new', 'G.C.E O/L', 'Single', 'Normal', 'Fast-Track Approved by thilina. Validated by AI Bot Verification Engine (Score: 95%).', NOW()) ON DUPLICATE KEY UPDATE `status`=VALUES(`status`);
INSERT INTO `applications` (`application_id`, `applicant_id`, `application_type`, `status`, `assigned_officer`, `application_reason`, `marital_status`, `service_type`, `remarks`, `submitted_at`) VALUES (2, 2, 'New', 'Processing', 'thilinapak', 'G.C.E O/L', 'Single', 'Normal', 'New citizen online submission.', NOW()) ON DUPLICATE KEY UPDATE `status`=VALUES(`status`);
INSERT INTO `applications` (`application_id`, `applicant_id`, `application_type`, `status`, `assigned_officer`, `application_reason`, `marital_status`, `service_type`, `remarks`, `submitted_at`) VALUES (3, 3, 'New', 'Documents-Required', 'Officer Wickramasinghe', 'Wallet Got Stolen', 'Single', '1-Day', '[Action Required: Re-upload Birth Certificate] [Action Required: Re-upload Birth Certificate] New citizen online submission.', NOW()) ON DUPLICATE KEY UPDATE `status`=VALUES(`status`);
INSERT INTO `applications` (`application_id`, `applicant_id`, `application_type`, `status`, `assigned_officer`, `application_reason`, `marital_status`, `service_type`, `remarks`, `submitted_at`) VALUES (9003, 9002, 'New', 'Documents-Required', 'Document Handling Officer Silva', 'G.C.E O/L', 'Single', 'Normal', '[Action Required: Re-upload Other Supporting Document] test', NOW()) ON DUPLICATE KEY UPDATE `status`=VALUES(`status`);

SET FOREIGN_KEY_CHECKS = 1;
