# Server Port
server.port=5000

# Application Name
spring.application.name=NexusGov Identity Card System

# MySQL DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/identity_card_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=nexusgov_identity_jwt_secret_key_2026_super_long_for_hmac_sha256_requirement
app.jwt.expiration-ms=604800000

# Gmail SMTP (OTP Emails)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nexus.government.id.card@gmail.com
spring.mail.password=zsaejcdnypkrgszh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Logging
logging.level.com.nexusgov=INFO
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=WARN
